Fix Grammar and remove errors
thedaviddias/Front-End-Checklist pull request #512
Opened 2023-08-14 08:28 UTC by iShashank04

**Fixes**: #

🚨 Please review the [guidelines for contributing](CONTRIBUTING.md) and our [code of conduct](../CODE_OF_CONDUCT.md) to this repository. 🚨
**Please complete these steps and check these boxes (by putting an x inside the brackets) before filing your PR:**

- [ ] Check the commit's or even all commits' message styles matches our requested structure.
- [ ] Check your code additions will fail neither code linting checks nor unit test.

#### Short description of what this resolves:

#### Proposed changes:

-
-
-

👍 Thank you!

2023-08-16 00:31 UTC, bitcoinfinancier approved these changes

2023-10-04 15:55 UTC, grejojoby requested changes
Other changes seems fine.

2023-10-04 15:55 UTC, grejojoby commented on CODE_OF_CONDUCT.md
> +* Publishing other's private information, such as a physical or electronic address, without explicit permission
This is not grammatically correct. others' is rightly used already. 

others' stands for a plural usage, which is correct already.

2023-10-04 15:55 UTC, grejojoby commented on README.md
> +* [ ] **HTML Lint:** ![High][high_img] I use tools to help me analyze any issues I could have with my HTML code.
You should use "in" instead of "with".

2023-10-04 15:55 UTC, grejojoby commented on README.md
> +* [ ] **HTML Lint:** ![High][high_img] I use tools to help me analyze any issues I could have with my HTML code.
```suggestion
* [ ] **HTML Lint:** ![High][high_img] I use tools to help me analyze any issues I could have in my HTML code.
```

2023-12-09 01:48 UTC, closed without merging